import React from 'react';
import Menu from '@/components/molecules/menu/menu'
import MyFooter from '@/components/molecules/footer/footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <>
      <Menu />
      <div>{children}</div>
      <MyFooter />
    </>
  );
};

export default RootLayout;